### ISSUE TITLE
Pippo demos don't build due to error in maven repo

### ISSUE THREAD

**Issue by realulim** [decebals/pippo-demo#14]
pippo-demo-parent 0.7.0-SNAPSHOT depends on a pippo-demo 0.7.0-SNAPSHOT, but that is not present:

https://oss.sonatype.org/content/repositories/snapshots/ro/pippo/pippo-parent/

**Comment by decebals** [comment]
Thanks! I will resolve all opened issues this weekend.

**Comment by decebals** [comment]
Fixed by commit b68945f.
