### ISSUE TITLE
how to config initial parameter without xml using servlet3.x

### ISSUE THREAD

**Issue by liu-shiyuan** [decebals/pippo-demo#16]

**Comment by liu-shiyuan** [comment]
I saw a web.xml in your demo project, I just wonder how can I programmatically adding and configuring a web project using Pippo.

**Comment by decebals** [comment]
The idea is that your Pippo application can be packed in two modes:
- java application (a jar with a main class - class that contains public static **main** method)
- web application (a war with a web.xml file inside)

In most of the cases you will use first variant (it's more easy to deploy, run or debug your application).
If you have a constraint that your application should be deployed in a legacy web servlet container (for example an application server like WebSphere) and it's only a part from the whole application (you use EJB for example) then you will use the second variant (but I recommend you to use first variant for a fast development).

So, web.xml from the demo project is used to pack the application in a war. See http://www.pippo.ro/dev/quickstart.html for some details.

Related to your question, you can "move" your initial parameters from wb.xml in `application.properties`. See http://www.pippo.ro/doc/settings.html.

**Comment by liu-shiyuan** [comment]
Problem solved, many thanks for your answer.
