### ISSUE TITLE
Use `pippo.GET(...)` instead of `pippo.getApplication().GET(...)`

### ISSUE THREAD

**Issue by decebals** [decebals/pippo-demo#9]
For example:

```java
public class HelloWorld {

    public static void main(String[] args) {
        Pippo pippo = new Pippo();
//        pippo.getApplication().GET("/", (routeContext) -> routeContext.send("Hello World!"));
       pippo.GET("/", (routeContext) -> routeContext.send("Hello World!")); // <<<
        pippo.start();
    }

}
```

And same operation for POST, ...

**Comment by munendrasn** [comment]
@decebals ,
Say /test/{main}?action=val
how to get query parameters from the url

**Comment by decebals** [comment]
`routeContext.getParameter(<your_param_name_here>)`

**Comment by decebals** [comment]
If you want something with a fine granularity you ca use `routeContext.getRequest()` and on Request you can call `getQueryParameter(name)` or `getQueryParameters()` or `getPathParameter(name)` or `getPathParameters()`
